### ISSUE TITLE
Cannot process earlier transaction?

### ISSUE THREAD

**Issue by swissarmybox** [eprbell/rp2#8] opened 2022-02-11 01:06 UTC
I have transactions in IN:
- 2021-01-03T23:40:42Z,  Buy, 1.0
- 2021-11-06T17:42:38Z,  Buy, 0.05
- 2021-11-06T17:53:04Z,  Buy, 0.05

and transactions in OUT:
- 2021-01-13T23:25:01Z, Sell, 1.0

Upon generation, I see a log being raised
RP2ValueError9 TImestamp (rp2.rp2_error.RP2ValueError: Timestamp 2021-01-13 23:25:01+00:00 of taxable_event is earlier than timestamp 2021-11-06 17:42:38+00:00 of acquired_lot: GainLoss:)

Seems it gets confused on the dates

**Comment by eprbell** [comment] 2022-02-11 03:47
Thanks for opening an issue! I need more information in order to understand what is happening: 
- would you be able to attach an (anonymized) file that reproduces the problem?
- are these all the transactions you have or are there more? I need to know the full context to understand why the error message is being given.
- are you using FIFO or LIFO?
- what version of RP2 are you using?

**Comment by eprbell** [comment] 2022-02-11 08:34
I'm not able to reproduce the issue. I created an input ODS file with the transactions you indicated + its respective config file ([both attached](https://github.com/eprbell/rp2/files/8047096/issue8.zip)): I then used them with RP2, which computes and generates results correctly both with FIFO and LIFO. 

Here are the command lines I used:
* rp2_us -m fifo -o output/ -p issue8_ issue8.config issue8.ods
* rp2_us -m lifo -o output/ -p issue8_ issue8.config issue8.ods

I think you may have extra transactions in your file: the error is probably telling you that you are selling lots that have not been bought yet, but I would have to see the file to be sure.

**Comment by eprbell** [comment] 2022-02-11 23:43
I was able to reproduce the error message by adding one single OUT transaction before the one you indicated (see picture below): the error message is correct and not an RP2 bug.
![Screen Shot 2022-02-11 at 12 05 08 PM](https://user-images.githubusercontent.com/77937475/153683264-00f4343c-0de1-4b62-9276-590630bbeb5e.png)

The error is rightly saying that some lot fractions are sold before they were acquired (which is not allowed). Here are the details of the computation, using the example from the picture and assuming FIFO accounting:
* 0.01 from OUT 2021-01-12 is mapped to IN 2021-01-03 (leaving 0.99 in that lot)
* 0.99 from OUT 2021-01-13 is mapped to the 0.99 leftover of IN 2021-01-03 (exhausting the lot)
* 0.01 leftover from  OUT 2021-01-13 is mapped to the next IN lot, which is 2021-11-06

However the last step triggers the error, because the date of the IN lot is later than the date of the OUT lot, which denotes an impossibility.

This is not a bug: it's just pointing to an inconsistency in the input data (it has been entered incorrectly or perhaps some transactions are missing).

Attaching the modified ODS with the extra OUT transaction: [issue8_repro.zip](https://github.com/eprbell/rp2/files/8051327/issue8_repro.zip).

I think this may be what's happening with your data as well, however if you think your case is different than what was explained above, please attach (or send) a file that reproduces the problem and I'll take a look.

**Comment by eprbell** [comment] 2022-02-12 19:15
Closing the issue.

**Closed by eprbell** 2022-02-12 19:15 UTC

**Comment by swissarmybox** [comment] 2022-02-13 23:28
Thank you! Sorry I haven't had time to upload my data yet. I will check what you found and confirmed it! Thanks again
