### ISSUE TITLE
Remainder of acquired lot does not seem to be carried over

### ISSUE THREAD

**Issue by macanudo527** [eprbell/rp2#48] opened 2022-07-25 13:34 UTC
I have some small BTC transactions:

BUY 0.00032667 crypto_in
SELL 0.00032600 crypto_out_with_fee
--- Wallet contains 0.00000067 BTC
BUY 0.00147452 crypto_in
--- Wallet now contains 0.00147519 BTC
SELL 0.00147500 crypto_out_with_fee
BUY
 0.00162737 <- RP2 stops here and complains that the taxable event (previous Sell) is earlier than this acquired lot.

It appears that RP2 doesn't carry over the remainder. RP2 supports splitting lots right? Maybe I'm misunderstanding tax law.

**Comment by eprbell** [comment] 2022-07-25 14:06
RP2 does support lot splitting, but that error typically means that some lot fraction is being sold before being acquired. A few questions:
* do you have other transactions before the ones you mentioned?
* can you share the timestamps of the transactions?
* what accounting method are you using?

Do you have a small repro file? If so I can look into it with the debugger.

**Comment by macanudo527** [comment] 2022-07-25 23:59
Here is the .ods/.config with BTC isolated, which is what I'm having issues with. I was using FIFO just to test the validity of the information I was getting back from the CCXT converter / Binance plugin. (I got it to output the report btw)

There are no transactions before these 5.

[binance_crypto_data.ods](https://github.com/eprbell/rp2/files/9185447/binance_crypto_data.ods)
[binance_crypto_data_config.zip](https://github.com/eprbell/rp2/files/9185470/binance_crypto_data_config.zip)

**Comment by eprbell** [comment] 2022-07-26 02:29
Thanks for the repro! Happily this is not a RP2 bug, however I think this behavior needs to be documented better in [this FAQ](https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#how-to-represent-fiat-vs-crypto-transaction-fees): I'll fix that. As it is I can understand that it would generate confusion, so thanks for reporting this.

Here's what happened. I kept the first 3 IN transactions and the first 2 OUT transactions and deleted the rest (is this correct?) and I was able to reproduce the problem. The IN transactions have a crypto fee, which is paid out of the IN transaction crypto amount: RP2 models this by creating an [artificial OUT transaction](https://github.com/eprbell/rp2/blob/main/src/rp2/ods_parser.py#L201) on the fly with the same timestamp as the IN transaction. This reduces the final amount of the IN transaction.

Note that:
* if the fee was paid in fiat, this wouldn't occur (and no artificial OUT transaction would be created);
* crypto fees are supported and OK to use but they have the behavior described above.

So here's a detailed description of how and why the exception is raised:
- IN: 2021-04-10 05:18:45 +0000: 0.00032667 - 0.00000033 = 0.00032634
- OUT: 2021-04-14 04:43:00 +0000: 0.000326
- at this point the balance is 0.00000034
- IN: 2021-04-20 23:14:35 +0000: 0.00147452 - 0.00000148 = 0.00147304
- at this point the balance is 0.00147338
- OUT: 2021-04-21 23:12:05 +0000: 0.001475
- at this point we're trying to sell more than we have, so RP2 looks for the next IN lot, which happens to be in the future (2021-04-25 20:48:59): this causes the error
- IN: 2021-04-25 20:48:59 +0000: 0.00162737 - 0.00000163 = 0.00162574

Hope this helps but let me know if you have more questions or comments. BTW, what was the issue with output generation?

**Comment by eprbell** [comment] 2022-07-26 02:37
I updated [the FAQ](https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#how-to-represent-fiat-vs-crypto-transaction-fees) with a description of the above behavior.

**Comment by eprbell** [comment] 2022-07-26 02:45
Additional information on [fee-only OUT transactions](https://github.com/eprbell/rp2/blob/main/docs/user_faq.md#how-to-handle-fee-only-defi-transactions), in case it's of interest.

**Comment by macanudo527** [comment] 2022-07-26 07:27
OK, I guess I got confused. I thought crypto_in was the total crypto that the holder received, and the fee is on top of that. So, If you bought 1 bitcoin for $21,000, the crypto_in would be 0.99 BTC, the crypto_fee is 0.01 BTC. But, that doesn't seem to be the case?

**Comment by eprbell** [comment] 2022-07-26 07:55
The main point is that the crypto fee for in transactions must be coming from somewhere (your crypto stash). As such it is modeled as an extra out-transaction, because it affects the in-out flow. So in the example you gave, your crypto in would be 1 and your crypto fee would be 0.01. The way to read it is: 1 btc came in and 0.01 went out for the fee. If the fee was fiat all this wouldn't apply, because the fiat fee would come out of a different stash (the fiat one which RP2 doesn't track). 

I haven't seen crypto fees in in-transactions before (all I saw was fiat fees). I wanted to double check that binance actually requires crypto fees i

**Comment by eprbell** [comment] 2022-07-26 07:56
Closed by mistake

**Comment by eprbell** [comment] 2022-07-26 16:34
Cool, thanks for the explanation.

**Comment by eprbell** [comment] 2022-07-28 14:26
Ok to close this?

**Comment by eprbell** [comment] 2022-08-01 05:38
This seems resolved, but feel free to reopen if you have more comments or feedback.

**Closed by eprbell** 2022-08-01 05:38 UTC
